// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/DevKayoS/go-lambda/internal/models"
)

// tokenService is an autogenerated mock type for the tokenService type
type tokenService struct {
	mock.Mock
}

// Auth provides a mock function with given fields: ctx, gr
func (_m *tokenService) Auth(ctx context.Context, gr models.GenerateTokenRequest) (string, error) {
	ret := _m.Called(ctx, gr)

	if len(ret) == 0 {
		panic("no return value specified for Auth")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, models.GenerateTokenRequest) (string, error)); ok {
		return rf(ctx, gr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, models.GenerateTokenRequest) string); ok {
		r0 = rf(ctx, gr)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, models.GenerateTokenRequest) error); ok {
		r1 = rf(ctx, gr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// newTokenService creates a new instance of tokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *tokenService {
	mock := &tokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
