// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	pgstore "github.com/DevKayoS/go-lambda/internal/pgstore"
	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

// GetUserByEmail provides a mock function with given fields: ctx, email
func (_m *UserRepository) GetUserByEmail(ctx context.Context, email string) (pgstore.User, error) {
	ret := _m.Called(ctx, email)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByEmail")
	}

	var r0 pgstore.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (pgstore.User, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) pgstore.User); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(pgstore.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserWithPermissionsById provides a mock function with given fields: ctx, id
func (_m *UserRepository) GetUserWithPermissionsById(ctx context.Context, id int64) (pgstore.GetUserWithPermissionsByIdRow, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserWithPermissionsById")
	}

	var r0 pgstore.GetUserWithPermissionsByIdRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (pgstore.GetUserWithPermissionsByIdRow, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) pgstore.GetUserWithPermissionsByIdRow); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(pgstore.GetUserWithPermissionsByIdRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// InsertUser provides a mock function with given fields: ctx, arg
func (_m *UserRepository) InsertUser(ctx context.Context, arg pgstore.InsertUserParams) (int64, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for InsertUser")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pgstore.InsertUserParams) (int64, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pgstore.InsertUserParams) int64); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, pgstore.InsertUserParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ListUser provides a mock function with given fields: ctx
func (_m *UserRepository) ListUser(ctx context.Context) ([]pgstore.ListUserRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListUser")
	}

	var r0 []pgstore.ListUserRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]pgstore.ListUserRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []pgstore.ListUserRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pgstore.ListUserRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
