// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pgstore "github.com/DevKayoS/go-lambda/internal/pgstore"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// CreateUser provides a mock function with given fields: ctx, body
func (_m *UserService) CreateUser(ctx context.Context, body pgstore.InsertUserParams) error {
	ret := _m.Called(ctx, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pgstore.InsertUserParams) error); ok {
		r0 = rf(ctx, body)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetMe provides a mock function with given fields: ctx, userID
func (_m *UserService) GetMe(ctx context.Context, userID int64) (pgstore.GetUserWithPermissionsByIdRow, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMe")
	}

	var r0 pgstore.GetUserWithPermissionsByIdRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (pgstore.GetUserWithPermissionsByIdRow, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) pgstore.GetUserWithPermissionsByIdRow); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(pgstore.GetUserWithPermissionsByIdRow)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// List provides a mock function with given fields: ctx
func (_m *UserService) List(ctx context.Context) ([]pgstore.ListUserRow, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []pgstore.ListUserRow
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]pgstore.ListUserRow, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []pgstore.ListUserRow); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pgstore.ListUserRow)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserService creates a new instance of UserService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserService {
	mock := &UserService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
