// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package pgstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, created_at, updated_at, role_id FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
	)
	return i, err
}

const getUserWithPermissionsById = `-- name: GetUserWithPermissionsById :one
SELECT 
    u.id,
    u.name,
    u.email,
    r.name as role_name
FROM users u
LEFT JOIN roles r ON u.role_id = r.id
WHERE u.id = $1
`

type GetUserWithPermissionsByIdRow struct {
	ID       int64       `json:"id"`
	Name     string      `json:"name"`
	Email    string      `json:"email"`
	RoleName pgtype.Text `json:"role_name"`
}

func (q *Queries) GetUserWithPermissionsById(ctx context.Context, id int64) (GetUserWithPermissionsByIdRow, error) {
	row := q.db.QueryRow(ctx, getUserWithPermissionsById, id)
	var i GetUserWithPermissionsByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.RoleName,
	)
	return i, err
}

const insertUser = `-- name: InsertUser :one
INSERT INTO users (name, email, password)
VALUES ($1, $2, $3)
RETURNING id
`

type InsertUserParams struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

func (q *Queries) InsertUser(ctx context.Context, arg InsertUserParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertUser, arg.Name, arg.Email, arg.Password)
	var id int64
	err := row.Scan(&id)
	return id, err
}
